from time import sleep
n = int(input('Qual número quer saber a tabuada? '))
print ('-#-' * 3)
print ('\033[1;32mTabuada do', n)

print ('\033[m-#-' * 3)

print (n, 'x 1 =', n * 1)
sleep(2)
print (n, 'x 2 =', n * 2)
sleep(2)
print (n, 'x 3 =', n * 3)
sleep(2)
print (n, 'x 4 =', n * 4)
sleep(2)
print (n, 'x 5 =', n * 5)
sleep(2)
print (n, 'x 6 =', n * 6)
sleep(2)
print (n, 'x 7 =', n * 7)
sleep(2)
print (n, 'x 8 =', n * 8)
sleep(2)
print (n, 'x 9 =', n * 9)
sleep(2)
print (n, 'x 10 =', n * 10)
print ()
sleep(2)
print ('-#-' * 3)
print ('Fim')
print ('-#-' * 3)
sleep(1)